---
- name: Run Test App
  hosts: all
  gather_facts: True
  tasks:
    - name: App install
      copy: 
        src:  ansible/test_app.sh
        dest: /tmp/
        owner: root
        group: root
 
    
